language: java
branches:
  only:
    - master
    - ode-1.3.x
jdk:
  - oraclejdk7
rvm:
  - 1.9.3
install:
  - rvm use 1.9.3
  - gem install bundler
  - bundle install
env:
  - TEST_PORTS=9999,7171
script: buildr clean package junit:report test=all JAVADOC=off
