language: java
branches:
  only:
    - master
    - ode-1.3.x
jdk:
  - oraclejdk7
rvm:
  - 1.9.3
install:
  - rvm use 1.9.3
  - gem install bundler
  - bundle install
cache:
  bundler: true
  directories:
    - $HOME/.m2
before_script:
  - mysql -e 'create database ode-hib;'
  - mysql -e 'create database ode-jpa;'
env:
  - TEST_PORTS=8888,7171
script: buildr clean package JAVADOC=off
